services:
    card-server:
        image: card-server 
        command: sh -c "python -m flask run -p 5001 -h 0.0.0.0"
        ports:
            - 5001:5001

        networks:
            - app-comm

        environment:
            - FLASK_APP=card-server
            - FLASK_ENV=development

        volumes:
            - ./card-server:/server/

        deploy:
            resources:
                reservations:
                    devices:
                        -   driver: nvidia
                            count: 1
                            capabilities: [gpu]


    mse-factory:
        image: mse2

        

    discord-bot:
        image: discord-app
        command: sh -c "npm run register && npm run start"
        ports:
            - 5000:5000

        networks:
            - app-comm

        volumes:
            - ./discord-app:/discord-app
    
volumes:
    card-storage:
    pip-installs:

networks:
    app-comm:
        driver: bridge